#
# Installs Alfresco to the specified hosts.
#
# Requires Alfresco distribution archive, Tomcat archive, and AOS archive to
# reside in files/third-party.
#
# Custom AMPs should be placed in files/third-party/amps and files/third-party/amps_share.
#
# Install location depends on alf_home, alf_install_dir, and tomcat_dir.
#
---
- hosts: '{{ hosts }}'
  remote_user: alfresco
  become: yes
  become_method: su
  become_user: alfresco
  tasks:
    - include_tasks: tasks/doInstallTomcat.yml
    - include_tasks: tasks/doInstallActivemq.yml
    - include_tasks: tasks/doInstallAlfresco.yml
    - include_tasks: tasks/doInstallPDFRenderer.yml
    - include_tasks: tasks/doCopyAmps.yml
    - include_tasks: tasks/doApplyAmps.yml
    - include_tasks: tasks/doCopyGlobalProperties.yml
    - include_tasks: tasks/doCopyTomcatConfig.yml
    - include_tasks: tasks/doCopyShareConfig.yml
    - include_tasks: tasks/doCopyAlfrescoConfig.yml
